image: node:14.17.1

stages:
  - test

test:
  stage: test
  except:
    - pushes
    - tags
    - branches
  script:
    - cd packages/backend
    - yarn
    - yarn test --ci
  tags:
    - kubernetes
