image: node:14.17.1

stages:
  - test

test:
  stage: test
  only:
    refs:
      - merge_requests
  except:
    - push
    - tags
  script:
    - cd packages/backend
    - yarn
    - yarn test --ci
  tags:
    - kubernetes
